# Generated by Django 5.0.3 on 2024-03-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_schedule_doctor'),
        ('ratings', '0002_alter_rating_doctor'),
        ('users', '0006_delete_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
