# Generated by Django 5.0.3 on 2024-03-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, default='/profile.jpeg', null=True, upload_to='profile_images/'),
        ),
    ]
