### Register example
POST http://127.0.0.1:8000/auth/register/
Content-Type: application/json

{
    "username": "al2i",
    "password": "123456",
    "first_name": "ali",
    "last_name": "mostafa",
    "email": "al2i@example.com",
    "is_patient": false,
    "is_doctor": true,
    "phone": "12345",
    "age": 35,
    "dob": "1989-01-01",
    "address": "123 Example St",
    "city": "Exampleville",
    "gender": "M"
}
###login example

POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

{
    "username": "ali55",
    "password": "123456"
}
### test example


GET http://127.0.0.1:8000/auth/test/
Content-Type: application/json
Authorization: Token b64b85c8023e683422da75bd4884f968c3f78204


### logout example
POST http://127.0.0.1:8000/auth/logout/
Content-Type: application/json
Authorization: Token 3ede88cc1730ff4c59c18a0cfe0d3d07ef457fd9


### rating example
POST http://127.0.0.1:8000/ratings/ratings/
Content-Type: application/json

{
    "doctor": 2,
    "user": 1,
    "rating": 4,
    "comment": "Great experience with the doctor!"
}


### get rating example
PUT http://127.0.0.1:8000/ratings/ratings/1/
Content-Type: application/json

{
    "doctor": 2,
    "user": 1,
    "rating": 4,
    "comment": "Great expe454rience with the doctor!",
    "created_at": "2024-03-12T22:47:52.391623Z"
}
### delete rating example
DELETE http://127.0.0.1:8000/ratings/ratings/1/


### get all patients
GET http://127.0.0.1:8000/auth/patients/


### get all doctors needed
GET http://127.0.0.1:8000/doctors/doctors/

### get patient by id
GET http://127.0.0.1:8000/auth/users/10/

### get doctor by id
GET http://127.0.0.1:8000/doctors/doctor/1/

### Delete doctor by id
DELETE http://127.0.0.1:8000/doctors/doctor/1/

### Delete patient by id
DELETE http://127.0.0.1:8000/auth/users/1/

### Update users main info by id
PUT http://127.0.0.1:8000/auth/users/10/
Content-Type: application/json

{
    "username": "ali2020",
    "first_name": "ali22020",
    "last_name": "mostafa",
    "email": "aliss2ss@example.com",
    "last_name": "mostafa",
}

### Update doctor profile by id
PUT http://127.0.0.1:8000/doctors/doctor/1/
Content-Type: application/json

{
    "specialization": "Cardiology",
    "bio": "I has a master degree in cardiology",
    "degree": null,
    "area": "Cairo",
    "fees": 500
}

##################################################
### add schedule
POST http://127.0.0.1:8000/schedules/all_sch/
Content-Type: application/json

{
            "doctor":3,
            "day":"friday",
            "start_time":"10:00",
            "end_time":"12:00",
            "is_active":false
}

### get all schedules
GET  http://127.0.0.1:8000/schedules/all_sch/


### Update schedule by id
PUT http://127.0.0.1:8000/schedules/schedule/4/
Content-Type: application/json

{
            "doctor":3,
            "day":"sunday",
            "start_time":"10:00",
            "end_time":"12:00",
            "is_active":false
}

### Delete/ delete schedule by id
GET http://127.0.0.1:8000/schedules/schedule/1/

#############################################
### add appointment
POST http://127.0.0.1:8000/schedules/all_app/
Content-Type: application/json

{
    "schedule":1,
    "user":2,
    "create_at":"",
    "is_accepted":false
}


### get all appointment
GET  http://127.0.0.1:8000/schedules/all_app/


### Update appointment by id
PUT http://127.0.0.1:8000/schedules/appointment/1/
Content-Type: application/json

{
    
    "schedule": 1,
    "user": 2,
    "create_at": "2024-03-12T23:33:52.655234Z",
    "is_accepted": true
}

### Delete/ delete appointment by id
DELETE  http://127.0.0.1:8000/schedules/appointment/1/


################################33
### rating example
POST http://127.0.0.1:8000/ratings/ratings/
Content-Type: application/json

{
    "doctor": 5,
    "user": 6,
    "rating": 4,
    "comment": "Great experience with the doctor!"
}
### get rating example
PUT http://127.0.0.1:8000/ratings/ratings/3/
Content-Type: application/json

{
    "doctor": 5,
    "user": 6,
    "rating": 5,
    "comment": "Great expe454rience with the doctor!",
    "created_at": "2024-03-12T22:47:52.391623Z"
}
### delete rating example
DELETE http://127.0.0.1:8000/ratings/ratings/3/

### get rating by doctor
GET http://127.0.0.1:8000/ratings/ratings/doctor/5/