# Generated by Django 5.0.3 on 2024-03-21 22:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_specialization_delete_specialization'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_date',
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='doctors.doctor'),
        ),
    ]
