# Generated by Django 5.0.3 on 2024-03-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_image_url_alter_offer_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image_url',
            field=models.ImageField(default='offer_images/offer.jpg', upload_to='offer_images/'),
        ),
    ]
