# Generated by Django 5.0.3 on 2024-03-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_fees'),
        ('offers', '0006_alter_offer_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='doctors.doctor'),
        ),
    ]
